### ISSUE TITLE
Add open source license for VoronoiHybrid

### ISSUE THREAD

**Issue by yungyuc** [Bichen07/VoronoiHybrid#1]
@Bichen07 , please add an open source license for your project. If you are not sure how to do it, see https://github.com/solvcon/modmesh.

**Comment by yungyuc** [comment]
@Bichen07 , any update?

**Comment by Bichen07** [comment]
sorry for forget. I have add a MIT License in my repository.

**Comment by yungyuc** [comment]
Using a PR will make it easier to track the work and update.  Feel free to close the issue at the time you like.
